// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyeusittahlyhyfptmcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5ZXVzaXR0YWhseWh5ZnB0bWNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4NTU1NDcsImV4cCI6MjA1ODQzMTU0N30.DR7EJgnc0vLLZyL9ZRC3nDccH73MbNK3WyA3253gVzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);